[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Markov-Notebook"
authors = [{name = "markov", email = "markov_engineer@163.com"}]
dynamic = ["version", "description"]
